from wpimath.units import inchesToMeters

# NOTE: MAKE SURE THESE ARE UP-TO-DATE

ARM_LENGTH = 0.6540246

CENTER_X_TO_ELEVATOR = -inchesToMeters(1)
PIVOT_TO_BOTTOM_OF_FIRST_STAGE = -0.1906
PIVOT_TO_GROUND = -0.3868

ELEVATOR_MAX_POSE = 1.03
ELEVATOR_MIN_POSE = 0.01

END_EFFECTOR_MIN_POSE = -0.23

COLLECTOR_STOWED_MIN_X = 0.23 + CENTER_X_TO_ELEVATOR
COLLECTOR_STOWED_HEIGHT = 0.6531 + PIVOT_TO_GROUND
COLLECTOR_DEPLOYED_HEIGHT = 0.30 + PIVOT_TO_GROUND
COLLECTOR_HEIGHT = COLLECTOR_DEPLOYED_HEIGHT

WHEEL_BASE_FWD = 0.527 / 2 - CENTER_X_TO_ELEVATOR  # between steer pivots
WHEEL_BASE_REV = -0.527 / 2 - CENTER_X_TO_ELEVATOR  # between steer pivots
WHEEL_PIVOT = 0.050 + PIVOT_TO_GROUND
WHEEL_RADIUS = inchesToMeters(3.95) / 2

BUMPER_FWD = 0.426 - CENTER_X_TO_ELEVATOR
BUMPER_REV = -0.426 - CENTER_X_TO_ELEVATOR
BUMPER_MIN_Y = 0.024 + PIVOT_TO_GROUND  # floor to bottom of bumpers
BUMPER_MAX_Y = 0.154 + PIVOT_TO_GROUND  # floor to top of bumpers

ELEVATOR_X_FWD = 0.1270
ELEVATOR_X_REV = -0.1270
ELEVATOR_HEIGHT = 0.8255 + PIVOT_TO_GROUND
